### ISSUE TITLE
Handling "See also"

### ISSUE THREAD

**Issue by pkej** [dominiclet/obsidian-note-definitions#62]
For now I've handled this by just embedding the text using `![[definitions#term|term]]`, but it would be nice to be able to use "See also term" and have that become a clickable link in the popup.

**Comment by dominiclet** [comment]
Thanks for the suggestion. Instead of the "See also term" interaction that you mentioned, I think it would be better if definitions are also underlined in the popup, and clicking on it links the user to the definition. This would achieve the same effect that you want, albeit in a different manner. What do you think?

**Comment by pkej** [comment]
Sounds good!

**Comment by dominiclet** [comment]
This is implemented in 0.21.0 and can be enabled via an optional setting.
